version: "3"
services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      ConnectionStrings__DefaultConnection: "${ConnectionStrings__DefaultConnection:?err}"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD:?err}"
      ACCEPT_EULA: "Y"
    #command: bash -c "/opt/mssql-tools/bin/sqlcmd -U SA -P $SA_PASSWORD -Q "USE master; IF db_id('CodeSanook') IS NULL CREATE DATABASE CodeSanook;""
