version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      ConnectionStrings__DefaultConnection: "${ConnectionStrings__DefaultConnection:?err}"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD:?err}"
      ACCEPT_EULA: "Y"